apiVersion: v1
kind: ConfigMap
metadata:
  name: academia-config
  namespace: academia
# Configuración NO sensible (puede ir en texto plano y versionarse en git)
data:
  APP_ENV: "training"
  APP_VERSION: "1.0.0"
