apiVersion: v1
kind: Service
metadata:
  name: {{ include "academia-app.name" . }}-service
  labels:
    {{- include "academia-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "academia-app.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
