apiVersion: v2
name: academia-app
description: Chart de Helm para la Academia DevOps App (curso DevOps y Contenedores)
type: application
version: 0.1.0          # versión del CHART
appVersion: "1.0.0"     # versión de la APLICACIÓN que empaqueta
